// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EasyRpc;
using Easyrpc.Agent.V1;
using Google.Protobuf;

namespace EasyRpc {
  public class AgentServiceClient {
    private readonly Transport _t;
    public AgentServiceClient(Transport t) { _t = t; }

    public async Task<HealthResponse> health(HealthRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Health", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return HealthResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListSessionsResponse> listSessions(ListSessionsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListSessions", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListSessionsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<CreateSessionResponse> createSession(CreateSessionRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/CreateSession", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return CreateSessionResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<GetSessionResponse> getSession(GetSessionRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/GetSession", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return GetSessionResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<DeleteSessionResponse> deleteSession(DeleteSessionRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/DeleteSession", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return DeleteSessionResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListMessagesResponse> listMessages(ListMessagesRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListMessages", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListMessagesResponse.Parser.ParseFrom(res.Body);
    }

    public async IAsyncEnumerable<PromptResponse> prompt(PromptRequest req) {
      var stream = await _t.OpenStream(new Request { Url = "/agent.v1.AgentService/Prompt", Body = req.ToByteArray() });
      await foreach (var m in stream) { yield return PromptResponse.Parser.ParseFrom(m); }
    }

    public async IAsyncEnumerable<WatchSessionResponse> watchSession(WatchSessionRequest req) {
      var stream = await _t.OpenStream(new Request { Url = "/agent.v1.AgentService/WatchSession", Body = req.ToByteArray() });
      await foreach (var m in stream) { yield return WatchSessionResponse.Parser.ParseFrom(m); }
    }

    public async IAsyncEnumerable<WatchSessionsResponse> watchSessions(WatchSessionsRequest req) {
      var stream = await _t.OpenStream(new Request { Url = "/agent.v1.AgentService/WatchSessions", Body = req.ToByteArray() });
      await foreach (var m in stream) { yield return WatchSessionsResponse.Parser.ParseFrom(m); }
    }

    public async Task<ForkResponse> fork(ForkRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Fork", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ForkResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<RenameResponse> rename(RenameRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Rename", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return RenameResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<SetModelResponse> setModel(SetModelRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/SetModel", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return SetModelResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<UndoResponse> undo(UndoRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Undo", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return UndoResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<StateResponse> state(StateRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/State", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return StateResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<MailboxResponse> mailbox(MailboxRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Mailbox", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return MailboxResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<UpdateSettingsResponse> updateSettings(UpdateSettingsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/UpdateSettings", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return UpdateSettingsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<InterruptResponse> interrupt(InterruptRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Interrupt", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return InterruptResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<CompactResponse> compact(CompactRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/Compact", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return CompactResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListProvidersResponse> listProviders(ListProvidersRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListProviders", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListProvidersResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListProvidersCatalogResponse> listProvidersCatalog(ListProvidersCatalogRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListProvidersCatalog", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListProvidersCatalogResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<RegisterProviderResponse> registerProvider(RegisterProviderRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/RegisterProvider", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return RegisterProviderResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<DiscoverGatewayModelsResponse> discoverGatewayModels(DiscoverGatewayModelsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/DiscoverGatewayModels", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return DiscoverGatewayModelsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<DeleteProviderResponse> deleteProvider(DeleteProviderRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/DeleteProvider", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return DeleteProviderResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<TestProviderResponse> testProvider(TestProviderRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/TestProvider", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return TestProviderResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListModelsResponse> listModels(ListModelsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListModels", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListModelsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListPresetsResponse> listPresets(ListPresetsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListPresets", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListPresetsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<UpsertPresetResponse> upsertPreset(UpsertPresetRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/UpsertPreset", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return UpsertPresetResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<DeletePresetResponse> deletePreset(DeletePresetRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/DeletePreset", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return DeletePresetResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<PreviewPresetResponse> previewPreset(PreviewPresetRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/PreviewPreset", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return PreviewPresetResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<GetConfigResponse> getConfig(GetConfigRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/GetConfig", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return GetConfigResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<SetConfigResponse> setConfig(SetConfigRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/SetConfig", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return SetConfigResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListToolsResponse> listTools(ListToolsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/ListTools", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListToolsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<GetToolConfigResponse> getToolConfig(GetToolConfigRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/GetToolConfig", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return GetToolConfigResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<SetToolConfigResponse> setToolConfig(SetToolConfigRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/SetToolConfig", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return SetToolConfigResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<SetExtensionConfigResponse> setExtensionConfig(SetExtensionConfigRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/SetExtensionConfig", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return SetExtensionConfigResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<UploadFileResponse> uploadFile(UploadFileRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/UploadFile", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return UploadFileResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<IngestFileResponse> ingestFile(IngestFileRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/IngestFile", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return IngestFileResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<GetFileResponse> getFile(GetFileRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/GetFile", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return GetFileResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<GetFileMetaResponse> getFileMeta(GetFileMetaRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/GetFileMeta", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return GetFileMetaResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<GetAgentConfigResponse> getAgentConfig(GetAgentConfigRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AgentService/GetAgentConfig", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return GetAgentConfigResponse.Parser.ParseFrom(res.Body);
    }

  }
}