// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EasyRpc;
using Easyrpc.Agent.V1;
using Google.Protobuf;

namespace EasyRpc {
  public class AdminServiceClient {
    private readonly Transport _t;
    public AdminServiceClient(Transport t) { _t = t; }

    public async Task<ListTenantsResponse> listTenants(ListTenantsRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/ListTenants", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListTenantsResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<CreateTenantResponse> createTenant(CreateTenantRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/CreateTenant", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return CreateTenantResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<UpdateTenantResponse> updateTenant(UpdateTenantRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/UpdateTenant", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return UpdateTenantResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<DeleteTenantResponse> deleteTenant(DeleteTenantRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/DeleteTenant", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return DeleteTenantResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<IssueTenantTokenResponse> issueTenantToken(IssueTenantTokenRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/IssueTenantToken", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return IssueTenantTokenResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<ListTenantTokensResponse> listTenantTokens(ListTenantTokensRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/ListTenantTokens", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return ListTenantTokensResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<RevokeTenantTokenResponse> revokeTenantToken(RevokeTenantTokenRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/RevokeTenantToken", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return RevokeTenantTokenResponse.Parser.ParseFrom(res.Body);
    }

    public async Task<RotateTenantTokenResponse> rotateTenantToken(RotateTenantTokenRequest req) {
      var res = await _t.Send(new Request { Url = "/agent.v1.AdminService/RotateTenantToken", Body = req.ToByteArray() });
      if (res.Error != null) throw res.Error;
      return RotateTenantTokenResponse.Parser.ParseFrom(res.Body);
    }

  }
}